# Site settings
title: Sam Jordan 
email: sfjordan@princeton.edu
description: > # this means to ignore newlines until "baseurl:"
  A series of posts discribing the computational misadventures of Sam Jordan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samjordan.me" # the base hostname & protocol for your site
github_username:  sfjordan

# Build settings
markdown: kramdown
